#!/usr/bin/env bash 
SERVER_PATH=/Users/raz/dev/hanbaba-server/
BUILD_JAR=hanbaba-server-1.0-SNAPSHOT.jar

cd ${SERVER_PATH}
./gradlew clean build
java -jar ${SERVER_APP_DIR}${ARTIFACT_NAME} >/dev/null 2>&1 &